### ISSUE TITLE
Dialog close X not visible

### ISSUE THREAD

**Issue by JoakimLofgren** [klarna/ui-react-components#40] opened 2016-06-13 12:36 UTC
When using `box-sizing: border-box;` the X disappears.

Is there a requirement on a certain box sizing for the ui-css-components to work properly ?

Some links:
* [Inheriting box-sizing Probably Slightly Better Best-Practice](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/)
* [* { Box-sizing: Border-box } FTW](http://www.paulirish.com/2012/box-sizing-border-box-ftw/)

**Comment by xaviervia** [comment] 2016-06-13 13:31
How are you using the `x`? It should be the `IconButton.CloseIcon` . Is it so? Can you paste a small snippet of how it's being consumed?

**Comment by ChristerGustavsson** [comment] 2016-06-13 14:27
jsx:
```javascript
import D from '@klarna/ui-react-components/components/Dialog'
import { CloseButton } from '@klarna/ui-react-components/components/IconButton'
```
```javascript
<D.Icon>
  <CloseButton id={`${this.props.name}-cancel-x`}
    className={styles.x}
    onClick={this.onCancel.bind(this)}/>
</D.Icon>
```

scss:
```css
.x {
  box-sizing: content-box; // @TODO remove until they fix their box-sizing
}
```

**Comment by xaviervia** [comment] 2016-06-13 14:43
Oh. This is because the border is actually used for the "glow" when active. I don't think there is a fix for this if we need to do the glow with border.  You can take a look at https://github.com/klarna/ui-css-components/blob/master/src/classes/illustration.scss#L48

Why do you need to do this?

> BTW, I'll soon merge https://github.com/klarna/ui-react-components/pull/26 which will allow you to override the whole style set for the component.

**Comment by ChristerGustavsson** [comment] 2016-06-13 15:19
The problem is that we've used:

````css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
````

This means that the `CloseButton` border and margin will behave very differently.

I even noticed while playing around on http://klarna.github.io/ui-react-components/#Buttons that you can barely press on the Iconic Buttons in the middle:

![sh7pne888j](https://cloud.githubusercontent.com/assets/894998/16012713/f8da0c9a-318a-11e6-860e-f37f1a29f354.gif)

**Comment by xaviervia** [comment] 2016-06-13 15:28
That's true. These components are designed to be placed in very specific
places. I think the simplest way forward for you could be to use a div
wrapping the icon instead, putting position relative on that one, then
putting position absolute on the icon and styling the wrapping div instead.

The reason this is strange is because while the component itself is SVG,
the active state is implemented with plain old CSS borders. It's an odd
combination, and without a wrapper div it was the only way we could come up
with.

**Comment by ChristerGustavsson** [comment] 2016-06-13 15:41
Maybe I wasn't clear with my example above. We've already "fixed" it for now with setting the box-sizing to content-box on the CloseButton.

It looks good now in the dialog and I believe the only thing we need is that it's set by the component itself instead.

**Comment by xaviervia** [comment] 2016-06-13 15:43
Oh, OK! Thanks. Should this maybe be on ui-css-components then?

mån 13 juni 2016 kl 17:41 skrev ChristerGustavsson <notifications@github.com

**Comment by ChristerGustavsson** [comment] 2016-06-14 05:34
Yeah, I guess that would be the easiest solution.

Den mån 13 juni 2016 17:43Xavier Via <notifications@github.com> skrev:

**Closed** 2016-06-22 09:38 UTC
